# Generated by Django 6.0 on 2025-12-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='surname',
        ),
    ]
