# Generated by Django 6.0 on 2025-12-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0002_rename_name_customer_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spin',
            name='prize',
            field=models.CharField(choices=[('free_delivery', 'pulsuz çatdırılma'), ('discount_5', '5% endirim'), ('discount_10', '10% endirim'), ('spin_again', 'yenidən fırlat'), ('no_prize', 'uduş yoxdur'), ('loyalty_card', 'loyallıq kartı'), ('one_plus_one', '1+1'), ('two_plus_one', '2+1')], max_length=31),
        ),
    ]
