# Generated by Django 6.0 on 2025-12-13 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0003_alter_spin_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='İstifadə yeri'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='spin.customer', verbose_name='Müştəri'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='İstifadə olunub'),
        ),
        migrations.AlterField(
            model_name='spin',
            name='prize',
            field=models.CharField(choices=[('free_delivery', 'pulsuz çatdırılma'), ('discount_5', '5% endirim'), ('discount_10', '10% endirim'), ('spin_again', 'yenidən fırlat'), ('no_prize', 'uduş yoxdur'), ('loyalty_card', 'loyallıq kartı'), ('discount_3_azn', '3 azn endirim kuponu'), ('discount_10_not_fish', 'kassa arxası məhsullara 10% endirim')], max_length=31, verbose_name='Uduş'),
        ),
    ]
