# Generated by Django 6.0 on 2025-12-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0004_spin_place_alter_spin_created_at_alter_spin_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spin',
            name='place',
            field=models.CharField(choices=[('poster_1', 'Poster 1'), ('poster_2', 'Poster 2'), ('poster_3', 'Poster 3'), ('poster_4', 'Poster 4'), ('poster_5', 'Poster 5'), ('poster_6', 'Poster 6'), ('poster_7', 'Poster 7'), ('poster_8', 'Poster 8'), ('poster_9', 'Poster 9'), ('poster_10', 'Poster 10')], max_length=20, verbose_name='Poster'),
        ),
    ]
