# Generated by Django 6.0 on 2025-12-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0005_alter_spin_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spin',
            old_name='place',
            new_name='poster',
        ),
    ]
