# Generated by Django 6.0 on 2026-01-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0006_rename_place_spin_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(choices=[('free_delivery', 'pulsuz çatdırılma'), ('discount_5', '5% endirim'), ('discount_10', '10% endirim'), ('spin_again', 'yenidən fırlat'), ('no_prize', 'uduş yoxdur'), ('loyalty_card', 'loyallıq kartı'), ('discount_3_azn', '3 azn endirim kuponu'), ('discount_10_not_fish', 'kassa arxası məhsullara 10% endirim')], max_length=31, verbose_name='Promo kod')),
                ('is_used', models.BooleanField(default=False, verbose_name='İstifadə olunub')),
                ('poster', models.CharField(choices=[('poster_1', 'Pilot Residence Icherisheher'), ('poster_2', 'Renessance Yashayish Sheher'), ('poster_3', 'Inkishaf Residence Ag Sheher'), ('poster_4', 'CasaMia Nesimi Bazari'), ('poster_5', 'Crown MTK'), ('poster_6', 'White Tower Khatai'), ('poster_7', 'Red MTK Khatai Icra Arxasi'), ('poster_8', 'Lexus Binasi Khatai'), ('poster_9', 'Abu Arena'), ('poster_10', 'Halal MTK'), ('poster_11', 'Gozel Baki Yashayish Kompleksi')], max_length=20, verbose_name='Poster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
        migrations.AlterField(
            model_name='spin',
            name='poster',
            field=models.CharField(choices=[('poster_1', 'Pilot Residence icherisheher'), ('poster_2', 'Renessance palace ag sheher'), ('poster_3', 'Inkishaf residence ag sheher'), ('poster_4', 'CasaMia Nesimi bazari'), ('poster_5', 'Teze Bazar binasi'), ('poster_6', 'White Tower Khatai'), ('poster_7', 'Red MTK Khatai Icra (Hakimiyyeti arxasi)'), ('poster_8', 'Lexus Binasi Khatai'), ('poster_9', 'Abu Arena'), ('poster_10', 'Rahat Marketin ustu'), ('poster_11', 'Social media')], max_length=20, verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to='spin.promocustomer', verbose_name='Müştəri'),
        ),
    ]
