# Generated by Django 6.0 on 2026-01-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0007_promocode_promocustomer_delete_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='promo_code',
            field=models.CharField(choices=[('poster_1', 'PILOT10'), ('poster_2', 'RENESS10'), ('poster_3', 'INKISAF10'), ('poster_4', 'CASAMIA10'), ('poster_5', 'CROWN10'), ('poster_6', 'WHITET10'), ('poster_7', 'REDMTK10'), ('poster_8', 'LEXUS10'), ('poster_9', 'ABUARE10'), ('poster_10', 'HALAL10'), ('poster_11', 'GOZELBK10')], max_length=31, verbose_name='Promo kod'),
        ),
    ]
