# Generated by Django 6.0 on 2026-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0008_alter_promocode_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='promo_code',
            field=models.CharField(max_length=31, verbose_name='Promo kod'),
        ),
    ]
