# Generated by Django 6.0 on 2026-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0009_alter_promocode_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Xidmət adı')),
            ],
        ),
        migrations.CreateModel(
            name='PriveCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Əlavə məlumat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested_in', models.ManyToManyField(blank=True, to='spin.service', verbose_name='Maraqlandığı xidmətlər')),
            ],
        ),
    ]
